# [[manager.prepend_keymap]]
# on   = [ "g", "i" ]
# run  = "plugin lazygit"
# desc = "run lazygit"
# 
# [[manager.prepend_keymap]]
# on  = [ "F" ]
# run = "filter --smart"
# desc = "Filter files"
# 
# [[manager.prepend_keymap]]
# on   = "f"
# run  = "plugin jump-to-char"
# desc = "Jump to char"

[mgr]
prepend_keymap = [
  { on = [ "F" ], run = "filter --smart", desc = "Filter files" },
  { on = "f", run = "plugin jump-to-char", desc = "Jump to char" },
  { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod selected files" },

  { on  = "M", run = "plugin mount", desc = "Select device then mount" },

  { on = [ "T" ], run = "plugin toggle-pane max-preview", desc = "Toggle maximize" },
  { on = [ "<C-n>" ], run = '''
      shell 'ripdrag "$@" -i -W 40 -H 40 -A -n -x 2>/dev/null &' --confirm
    ''' },
  { on = [ "C" ], run = "plugin ouch", desc = "Compress with ouch" },
]
