[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"

[preview]
wrap = "yes"

[opener]
extract = [
  { run = 'ouch d -y %*', desc = "Extract here with ouch", for = "windows" },
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
